name: Update readme # GitHub Actions 탭에서 확인할 수 있는 액션 이름

on: # jobs가 실행되어야 하는 상황 정의
  push:
    branches: [ "main" ] # main 브랜치에 push가 발생했을 때
  pull_request:

jobs: # 실제 실행될 내용
  build:
    runs-on: ubuntu-latest # 빌드 환경
    steps:
    - uses: actions/checkout@v3 # checkout
    - name: Setup Java JDK
      uses: actions/setup-java@v3 # setup-java
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        gradle-version: '7.3.3' # 원하는 Gradle 버전으로 변경
        arguments: jar
        
    - name: Run Jar File
      run: |
        java -jar ./build/libs/CodingTestPractice-1.0-SNAPSHOT.jar
    - name: Commit changes # 3) 추가된 파일 commit
      run: |
        git config --global user.name 'rkfcl' # 유저명
        git config --global user.email 'kwmkr6@gmail.com' # 유저 이메일
        git add -A
        git commit -am "auto update README.md" # 커밋 메시지
    - name: Push changes # 4) 메인에 푸시
      run: |
        git push
