name: Update readme

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
      with:
        gradle-version: '7.3.3'
        arguments: jar
    - name: Check for changes
      run: |
        git diff --quiet || exit 0
        exit 1
      continue-on-error: true
    - name: Commit changes
      run: |
        git config --global user.email 'kwmkr6@gmail.com'
        git add -A
        git commit -m "Auto update README.md"
    - name: Push changes
      if: success()
      run: |
        git push
